-- Create the JobsOpeningsDB database
CREATE DATABASE JobsOpeningsDB;
GO

-- Use the newly created database
USE JobsOpeningsDB;
GO

-- Create the LOCATIONS table
CREATE TABLE LOCATIONS(
	LOCATIONID INTEGER IDENTITY(1,1) PRIMARY KEY,
	LOCATIONTITLE VARCHAR(100) NOT NULL,
	LOCATIONCITY VARCHAR(100) NOT NULL,
	LOCATIONSTATE VARCHAR(100) NOT NULL,
	LOCATIONCOUNTRY VARCHAR(100) NOT NULL,
	LOCATIONZIP INTEGER NOT NULL
);
GO

-- Create the DEPARTMENTS table
CREATE TABLE DEPARTMENTS(
	DEPARTMENTID INTEGER IDENTITY(1,1) PRIMARY KEY,
	DEPARTMENTTITLE VARCHAR(100) NOT NULL
);
GO

-- Create the JOBS table
CREATE TABLE JOBS(
	JOBID INTEGER IDENTITY(1,1) PRIMARY KEY,
	JOBCODE AS 'JOB-' + RIGHT('0' + CAST(JOBID AS VARCHAR(8)), 3) PERSISTED NOT NULL,
	JOBTITLE VARCHAR(100) NOT NULL,
	JOBDESCRIPTION VARCHAR(1000) NOT NULL,
	POSTEDDATE DATETIME,
	CLOSINGDATE DATETIME,
	LOCATIONID INT NOT NULL FOREIGN KEY REFERENCES LOCATIONS(LOCATIONID),
	DEPARTMENTID INT NOT NULL FOREIGN KEY REFERENCES DEPARTMENTS(DEPARTMENTID)
);
GO